[package]
name = "ironos"
version = "0.0.0"
edition = "2021"
default-run = "ironos"

[build-dependencies]
bootloader = "0.11.4"
kernel = { path = "../kernel", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"
